// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GeneCloning",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "GeneCloning",
            targets: ["AppModule"],
            bundleIdentifier: "MadhavGulati.SwiftChallenge2022",
            teamIdentifier: "6DU75W3VAH",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Allow your camera in order to use AR to view your fish in real life!")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/joogps/IrregularGradient", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "IrregularGradient", package: "irregulargradient")
            ],
            path: ".",
            resources: [
                .process("Resources/pop.mp3"),
                .process("Resources/start.mp3"),
                .process("Resources/intro.mp3"),
                .process("Resources/ship.scn"),
                .process("Resources/texture.png")
            ]
        )
    ]
)
